# Github workflow to check python code

name: Python
on: [push]

jobs:
  # https://black.readthedocs.io/en/stable/integrations/github_actions.html
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
